import 'package:flutter/material.dart';
import 'package:webapp/screens/drawrr.dart';

class PrivacyPolicy extends StatefulWidget {
  PrivacyPolicy({Key? key}) : super(key: key);

  @override
  State<PrivacyPolicy> createState() => _PrivacyPolicyState();
}

class _PrivacyPolicyState extends State<PrivacyPolicy> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      drawer: Drawer(
        child: newdrawerpage(),
      ),
      backgroundColor: Colors.white,
      appBar: AppBar(
          backgroundColor: Colors.black,
          title: Column(
            children: [
              Row(
                children: [
                  //  IconButton(onPressed: (){   _scaffoldKey.currentState!.openDrawer();}, icon: Icon(Icons.menu)),
                  SizedBox(
                    width: 20,
                  ),
                  Text(
                    "Tengkolok Trading",
                    style: TextStyle(color: Colors.white, fontSize: 22),
                  ),
                ],
              ),
            ],
          )),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(12.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                height: 10,
              ),
              Text(
                'Privacy Policy',
                style: TextStyle(fontSize: 22),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'Privacy Policy',
                style: TextStyle(),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'Updated at 2020-09-07',
                style: TextStyle(),
              ),
              SizedBox(
                height: 45,
              ),
              Text(
                'Zahra (“we,” “our,” or “us”) is committed to protecting your privacy.  This Privacy Policy explains how your personal information is collected, used, and disclosed by Zahra.This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Zahra. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 45,
              ),
              Text(
                'Meanings',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'For this Privacy Policy:',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                ' -You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.-Company (referred to as either “Zahra”, “We”, “Us” or “Our” in this Agreement) refers to ,Website is referred to Zahra.-Service is referred to the app.-Service Provider means any natural or legal person who processes the data on behalf of Zahra. It refers to third-party companies or individuals employed by Zahra to facilitate the Service, to provide the Service on behalf of Zahra, to perform services related to the Service or to assist Zahra in analysing how the Service is used.-Third-party Social Media Service could be any website or social network website in which a User can log in or create an account to use the Service.-Personal Data is any information that relates to an identified or identifiable individual. -Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.-Device could be any device with internet who can access the service such as a mobile phone, a computer or a digital tablet. -Usage Data it’s referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the app.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'What Information Do We Collect?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                ' -Email address',
                style: TextStyle(),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                ' -Name / username',
                style: TextStyle(),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                ' -Social media profile information',
                style: TextStyle(),
              ),
              SizedBox(
                height: 45,
              ),
              Text(
                ' How Do We Use The Information We Collect?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 45,
              ),
              Text(
                'Any of the information we collect from you may be used in one of the following ways:',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                '  -To personalize your experience (your information helps us to better respond to your individual needs)-To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)-To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)-To process transactions-To administer a contest, promotion, survey or other site feature -To send periodic emails',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'When does Zahra use end user information from third parties?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Zahra will collect End User Data necessary to provide the Zahra services to our customers.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'When does Zahra use customer information from third parties?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Zahra customer, we receive information from a third party that provides automated fraud detection services to Zahra. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Do we share the information we collect with third parties?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the app in a shared location, and type of the device used to visit the app. They may aggregate information about our advertising and what you see on the app and then provide auditing, research and reporting for us and our advertisers. ',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations. ',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Where and when is information collected from customers and end users?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Zahra will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'How Do We Use Your Email Address?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'How Long Do We Keep Your Information?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We keep your information only so long as we need it to provide Zahra to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can’t identify you.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'How Do We Protect Your Information?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Zahra or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Could my information be transferred to other countries?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Zahra is incorporated in MY. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Is the information collected through the Zahra Service secure?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Can I update or correct my information?',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'The rights you have to request updates or corrections to the information Zahra collects depend on your relationship with Zahra. Personnel may update or correct their information as detailed in our internal company employment policies.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Sale of Business',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Zahra or any of its Corporate Affiliates (as defined herein), or that portion of Zahra or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Affiliates',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or indirectly controls, is controlled by or is under common control with Zahra, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Governing Law',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'This Privacy Policy is governed by the laws of MY without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'The laws of MY, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. Your use of the app may also be subject to other local, state, national, or international laws.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'By using Zahra or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Your Consent',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our app, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Links to Other Websites',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Cookies',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Zahra uses “Cookies” to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Blocking and disabling cookies and similar technologies',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Remarketing Services',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they’re “following” people around the internet by serving ads on the websites and platforms they use most.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Payment Details',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Kids’ Privacy',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Changes To Our Privacy Policy',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Third-Party Services',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third- Party Services”).You acknowledge and agree that Zahra shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Zahra does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties’ terms and conditions.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Information Regarding Your Data Protection Rights Under General Data Protection Regulation (GDPR)',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'For the purpose of this Privacy Policy, we are a Data Controller of your personal information.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'If you are from the European Economic Area (EEA), our legal basis for collecting and using your personal information, as described in this Privacy Policy, depends on the information we collect and the specific context in which we collect it. We may process your personal information because:',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                ' -We need to perform a contract with you, such as when you use our services -You have given us permission to do so -The processing is in our legitimate interests and it’s not overridden by your rights -For payment processing purposes-To comply with the law',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'If you are a resident of the European Economic Area (EEA), you have certain data protection rights. In certain circumstances, you have the following data protection rights:',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                '  -The right to access, update or to delete the personal information we have on you -The right of rectification -The right to object-The right of restriction -The right to data portability-The right to withdraw consent',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Please note that we may ask you to verify your identity before responding to such requests.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'You have the right to complain to a Data Protection Authority about our collection and use of your personal information. For more information, please contact your local data protection authority in the European Economic Area (EEA).',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'California Residents',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                '  -Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you. -Right to Equal Service. We will not discriminate against you if you exercise your privacy rights. -Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected. -Request that a business that sells a consumer’s personal data, not sell the consumer’s personal data.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.We do not sell the Personal Information of our users.For more information about these rights, please contact us.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Contact Us',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                'Don’t hesitate to contact us if you have any questions.',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
              Text(
                '-Via Email:  tengkolok.trading@gmail.com',
                style: TextStyle(),
              ),
              SizedBox(
                height: 5,
              ),
              Text(
                '-Via this Link:  https://tengkoloktrading.com/contact',
                style: TextStyle(),
              ),
              SizedBox(
                height: 25,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
